### ISSUE TITLE
Crash when trying to use SDL2 as renderer?

### ISSUE THREAD

**Issue by rcr1000** [libtcod/libtcod#2]
When trying to use the SDL2 renderer in `TCOD_console_init_root` (I'm using Visual Studio 2017), I get a "Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000." error immediately after the function is called. SDL(1) works fine.

I tried manually including the sdl2 headers, as well as manually linking the SDL2 library and includes to no avail.

**Comment by HexDecimal** [comment]
It's unlikely that this has to do with the including or linking of SDL2, those kind of issues would prevent the program from running at all.

Is there any more to the error then just the one line?

**Comment by rcr1000** [comment]
Ahh, good point. Yeah, it shouldn't be the SDL2 including/linking.

No, unfortunately the only other thing it tells me is where the original unhandled exception took place in memory. Here is the entirety of the information VS gives me:

`Unhandled exception at 0x00007FFF4EEAA388 in libtcod Test.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000. occurred`

**Comment by HexDecimal** [comment]
I've released a new version of libtcod which includes a `.pdb` file.  It might give more information on the error if it's loaded.

Also did you run the samples programs that are included in the releases?  Are those working at the same time your program is crashing?

**Comment by rcr1000** [comment]
I did test the samples, and they all worked perfectly fine. I tried digging into them a bit to figure out the problem, but I couldn't find anything that helped.

Will test the new version tomorrow and see what happens.

**Comment by HexDecimal** [comment]
I might need to see your code later so that I can reproduce the issue.

**Comment by rcr1000** [comment]
I'm happy to share it, but it is purely me trying to initialize the root console. The program crashes immediately after, no matter what. I tested it by putting a simple `int n = 1;` line after to confirm, and it still crashes immediately *after* the initialization, no matter what comes after.

**Comment by HexDecimal** [comment]
There is a new `TCOD_quit` function you must call after calling `TCOD_console_init_root`.  If you're using a new renderer then you must call `TCOD_quit` or the program will crash.

**Comment by rcr1000** [comment]
Good Lord, immediately after? I was under the impression that was just needed as a precaution before returning 0 from main.

**Comment by HexDecimal** [comment]
I was able to reproduce a crash by avoiding a call to `TCOD_set_custom_font`.  The new renderers don't support the default font at the moment.

**Comment by rcr1000** [comment]
Hmm, tested this out, and that still doesn't seem to fix it for me.

**Comment by HexDecimal** [comment]
You should post your code.  I can only guess what the problem is without it.

**Comment by rcr1000** [comment]
Sure, here is the whole code:
```
#include "libtcod.h"

int main() {

  TCODConsole::setCustomFont("PATH TO MY TTF");
  TCODConsole::initRoot(100, 100, "LIB", false, TCOD_RENDERER_SDL2);
  
  int num = 4; // A stopping point to confirm the error indeed occurs immediately after `initRoot`

  TCOD_quit();
  return 0;
}
```

**Comment by HexDecimal** [comment]
libtcod doesn't support TrueType at the moment.  I think the new renderers might not even be able to except anything other than a PNG file.

**Comment by rcr1000** [comment]
*facepalm* Yep, wasn't thinking about that.
